//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication6.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFlyService")]
    public interface IFlyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyService/Inovke", ReplyAction="http://tempuri.org/IFlyService/InovkeResponse")]
        string Inovke(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyService/Inovke", ReplyAction="http://tempuri.org/IFlyService/InovkeResponse")]
        System.Threading.Tasks.Task<string> InovkeAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlyServiceChannel : ConsoleApplication6.ServiceReference1.IFlyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlyServiceClient : System.ServiceModel.ClientBase<ConsoleApplication6.ServiceReference1.IFlyService>, ConsoleApplication6.ServiceReference1.IFlyService {
        
        public FlyServiceClient() {
        }
        
        public FlyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Inovke(string msg) {
            return base.Channel.Inovke(msg);
        }
        
        public System.Threading.Tasks.Task<string> InovkeAsync(string msg) {
            return base.Channel.InovkeAsync(msg);
        }
    }
}
