//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientContract.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFlyService")]
    public interface IFlyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyService/Fly", ReplyAction="http://tempuri.org/IFlyService/FlyResponse")]
        string Fly(string message);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFlyService/Fly", ReplyAction="http://tempuri.org/IFlyService/FlyResponse")]
        System.IAsyncResult BeginFly(string message, System.AsyncCallback callback, object asyncState);
        
        string EndFly(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlyServiceChannel : WcfClientContract.ServiceReference1.IFlyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FlyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlyServiceClient : System.ServiceModel.ClientBase<WcfClientContract.ServiceReference1.IFlyService>, WcfClientContract.ServiceReference1.IFlyService {
        
        private BeginOperationDelegate onBeginFlyDelegate;
        
        private EndOperationDelegate onEndFlyDelegate;
        
        private System.Threading.SendOrPostCallback onFlyCompletedDelegate;
        
        public FlyServiceClient() {
        }
        
        public FlyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<FlyCompletedEventArgs> FlyCompleted;
        
        public string Fly(string message) {
            return base.Channel.Fly(message);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginFly(string message, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFly(message, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndFly(System.IAsyncResult result) {
            return base.Channel.EndFly(result);
        }
        
        private System.IAsyncResult OnBeginFly(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string message = ((string)(inValues[0]));
            return this.BeginFly(message, callback, asyncState);
        }
        
        private object[] OnEndFly(System.IAsyncResult result) {
            string retVal = this.EndFly(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFlyCompleted(object state) {
            if ((this.FlyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FlyCompleted(this, new FlyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FlyAsync(string message) {
            this.FlyAsync(message, null);
        }
        
        public void FlyAsync(string message, object userState) {
            if ((this.onBeginFlyDelegate == null)) {
                this.onBeginFlyDelegate = new BeginOperationDelegate(this.OnBeginFly);
            }
            if ((this.onEndFlyDelegate == null)) {
                this.onEndFlyDelegate = new EndOperationDelegate(this.OnEndFly);
            }
            if ((this.onFlyCompletedDelegate == null)) {
                this.onFlyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFlyCompleted);
            }
            base.InvokeAsync(this.onBeginFlyDelegate, new object[] {
                        message}, this.onEndFlyDelegate, this.onFlyCompletedDelegate, userState);
        }
    }
}
